"""Data test."""
import os
import glob
import inspect
import pytest
from pathlib import Path

import cr8tor_metamodel.datamodel.cr8tor_metamodel as module
from linkml_runtime.loaders import yaml_loader

DATA_DIR_VALID = Path(__file__).parent / "data" / "valid"
DATA_DIR_INVALID = Path(__file__).parent / "data" / "invalid"

VALID_EXAMPLE_FILES = glob.glob(os.path.join(DATA_DIR_VALID, '*.yaml'))
INVALID_EXAMPLE_FILES = glob.glob(os.path.join(DATA_DIR_INVALID, '*.yaml'))

# Build case-insensitive lookup of all classes in the module.
# Schema class names may differ in case from
# the Python class names generated by gen-python (e.g. cr8tor to Cr8tor).
_CLASS_LOOKUP = {
    name.lower(): obj
    for name, obj in inspect.getmembers(module, inspect.isclass)
}


@pytest.mark.parametrize("filepath", VALID_EXAMPLE_FILES)
def test_valid_data_files(filepath):
    """Test loading of all valid data files."""
    target_class_name = Path(filepath).stem.split("-")[0]
    tgt_class = _CLASS_LOOKUP[target_class_name.lower()]
    obj = yaml_loader.load(filepath, target_class=tgt_class)
    assert obj
